# train
TRAIN_BATCH_SIZE: 10
VAL_BATCH_SIZE: 1
RESOLUTION: 1024
LR: 0.001
NUM_WORKERS: 8
EPOCHS: 200
TRAIN_PRINT: 100
VAL_PRINT: 100
SEED: 2

# model
MODEL: 'fasterrcnn_resnet18_fpn'
ENCODER_WEIGHTS:

# post processing
NMS_IOU: 0.05
CONF_THRESH: 0.3
RPN_FG_IOU_THRESH: 0.5
RPN_BG_IOU_THRESH: 0.5
PRE_NMS_TOP_N_TEST: 3

# data
DATA_ROOT: '../data/'
DATASET: 'sb_inc_negatives'
MODALITY: 'oct'
NUM_CLASSES: 2
AUGMENTATION: False